export const FETCH_CUSTOMER_ACCOUNT_FAILURE = 'GET_CUSTOMER_ACCOUNT_FAILURE';
export const FETCH_CUSTOMER_ACCOUNT_REQUEST = 'GET_CUSTOMER_ACCOUNT_REQUEST';
export const FETCH_CUSTOMER_ACCOUNT_SUCCESS = 'GET_CUSTOMER_ACCOUNT_SUCCESS';


export const CUSTOMER_TRANSFER_FAILURE = 'CUSTOMER_TRANSFER_FAILURE';
export const CUSTOMER_TRANSFER_SUCCESS = 'CUSTOMER_TRANSFER_SUCCESS';
export const CUSTOMER_TRANSFER_REQUEST = 'CUSTOMER_TRANSFER_REQUEST';

export const CUSTOMER_REQUEST_TRANSFER = 'CUSTOMER_REQUEST_TRANSFER';
export const CUSTOMER_REQUEST_TRANSFER_SUCCESS = 'CUSTOMER_REQUEST_TRANSFER_SUCCESS';
export const CUSTOMER_REQUEST_TRANSFER_FAILURE = 'CUSTOMER_REQUEST_TRANSFER_FAILURE';

export const VERIFY_CODE_REQUEST = 'VERIFY_CODE_REQUEST';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE';

export const SAVE_RECEIVER_FAILURE = 'SAVE_RECEIVER_FAILURE';
export const SAVE_RECEIVER_REQUEST = 'SAVE_RECEIVER_REQUEST';
export const SAVE_RECEIVER_SUCCESS =  'SAVE_RECEIVER_SUCCESS';