export const FETCH_CUSTOMER_ACCOUNT_FAILURE = 'GET_CUSTOMER_ACCOUNT_FAILURE';
export const FETCH_CUSTOMER_ACCOUNT_REQUEST = 'GET_CUSTOMER_ACCOUNT_REQUEST';
export const FETCH_CUSTOMER_ACCOUNT_SUCCESS = 'GET_CUSTOMER_ACCOUNT_SUCCESS';